spring:
  #  jwt:
  #    secret: hdqkwhdwqkjlfkeqjwrklqjdklsajklejqdkjqdjhn1@!#@#!@$@!$#%#@$^$%#@!$!lkfeqwklfdn@!#@!#

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      dialect : org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      format_sql: true

  autoconfigure:
    exclude: org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration

cloud:
  aws:
    region:
      static: ap-northeast-2